--- Every live cyberware record in the base game's TweakDB -- the list the
--- record reader walks. GENERATED from the installed `tweakdb.bin` +
--- `tweakdb_ep1.bin` (build 2.31) by the catalogue generator in
--- `scripts/research/cyberware-catalog`; the `Items.` prefix is dropped here
--- and put back by the reader. Deprecated records are left out.
-- @author XEROX710
--
-- SERVER ONLY, and data only: nothing here decides anything. A dedicated
-- server has no engine to ask what `Items.AdvancedCatPawsRare` is called, so
-- `server/reader.lua` hands these to a connected client in batches and keeps
-- what its live TweakDB answers. 1630 records; one table constructor, well
-- under the host's per-file load budget.

local M = OPX.Modules.Get('ripperdoc')

M.Records = M.Records or {}

M.Records.BUILD = '2.31'

M.Records.IDS = {
	'AdvancedAdaptiveStemCellsCommon', 'AdvancedAdaptiveStemCellsEpic',
	'AdvancedAdaptiveStemCellsEpicPlus', 'AdvancedAdaptiveStemCellsLegendary',
	'AdvancedAdaptiveStemCellsLegendaryPlus', 'AdvancedAdaptiveStemCellsLegendaryPlusPlus',
	'AdvancedAdaptiveStemCellsRare', 'AdvancedAdaptiveStemCellsRarePlus',
	'AdvancedAdaptiveStemCellsStatsShard', 'AdvancedAdaptiveStemCellsUncommon',
	'AdvancedAdaptiveStemCellsUncommonPlus', 'AdvancedAgileJointsCommon', 'AdvancedAgileJointsCommon2',
	'AdvancedAgileJointsCommon2Plus', 'AdvancedAgileJointsCommonPlus', 'AdvancedAgileJointsEpic',
	'AdvancedAgileJointsEpic2', 'AdvancedAgileJointsEpic2Plus', 'AdvancedAgileJointsEpicPlus',
	'AdvancedAgileJointsLegendary', 'AdvancedAgileJointsLegendary2',
	'AdvancedAgileJointsLegendary2Plus', 'AdvancedAgileJointsLegendary2PlusPlus',
	'AdvancedAgileJointsLegendaryPlus', 'AdvancedAgileJointsLegendaryPlusPlus',
	'AdvancedAgileJointsRare', 'AdvancedAgileJointsRare2', 'AdvancedAgileJointsRare2Plus',
	'AdvancedAgileJointsRarePlus', 'AdvancedAgileJointsStatsShard', 'AdvancedAgileJointsUncommon',
	'AdvancedAgileJointsUncommon2', 'AdvancedAgileJointsUncommon2Plus',
	'AdvancedAgileJointsUncommonPlus', 'AdvancedArasakaShadowMKICommon',
	'AdvancedArasakaShadowMKICommonPlus', 'AdvancedArasakaShadowMKIIIRare',
	'AdvancedArasakaShadowMKIIIRarePlus', 'AdvancedArasakaShadowMKIIUncommon',
	'AdvancedArasakaShadowMKIIUncommonPlus', 'AdvancedArasakaShadowMKIVEpic',
	'AdvancedArasakaShadowMKIVEpicPlus', 'AdvancedArasakaShadowMKVLegendary',
	'AdvancedArasakaShadowMKVLegendaryPlus', 'AdvancedArasakaShadowMKVLegendaryPlusPlus',
	'AdvancedBaseLowEnergyDeck', 'AdvancedBaseMidEnergyDeck', 'AdvancedBerserkC1MK1',
	'AdvancedBerserkC1MK1Plus', 'AdvancedBerserkC1MK2', 'AdvancedBerserkC1MK2Plus',
	'AdvancedBerserkC1MK3', 'AdvancedBerserkC1MK3Plus', 'AdvancedBerserkC1MK4',
	'AdvancedBerserkC1MK4Plus', 'AdvancedBerserkC1MK4PlusPlus', 'AdvancedBerserkC2MK1',
	'AdvancedBerserkC2MK1Plus', 'AdvancedBerserkC2MK2', 'AdvancedBerserkC2MK2Plus',
	'AdvancedBerserkC2MK3', 'AdvancedBerserkC2MK3Plus', 'AdvancedBerserkC2MK4',
	'AdvancedBerserkC2MK4Plus', 'AdvancedBerserkC2MK4PlusPlus', 'AdvancedBerserkC3MK3',
	'AdvancedBerserkC3MK3Plus', 'AdvancedBerserkC3MK4', 'AdvancedBerserkC3MK4Plus',
	'AdvancedBerserkC3MK5', 'AdvancedBerserkC3MK5Plus', 'AdvancedBerserkC3MK5PlusPlus',
	'AdvancedBerserkC4MK4', 'AdvancedBerserkC4MK4Plus', 'AdvancedBerserkC4MK5',
	'AdvancedBerserkC4MK5Plus', 'AdvancedBerserkC4MK5PlusPlus', 'AdvancedBioConductorsCommon',
	'AdvancedBioConductorsCommonPlus', 'AdvancedBioConductorsEpic', 'AdvancedBioConductorsEpicPlus',
	'AdvancedBioConductorsLegendary', 'AdvancedBioConductorsLegendaryPlus',
	'AdvancedBioConductorsLegendary_PlusPlus', 'AdvancedBioConductorsRare',
	'AdvancedBioConductorsRarePlus', 'AdvancedBioConductorsStatsShard',
	'AdvancedBioConductorsUncommon', 'AdvancedBioConductorsUncommonPlus', 'AdvancedBiomonitorCommon',
	'AdvancedBiomonitorCommonPlus', 'AdvancedBiomonitorEpic', 'AdvancedBiomonitorEpicPlus',
	'AdvancedBiomonitorLegendary', 'AdvancedBiomonitorLegendaryPlus',
	'AdvancedBiomonitorLegendaryPlusPlus', 'AdvancedBiomonitorRare', 'AdvancedBiomonitorRarePlus',
	'AdvancedBiomonitorStatsShard', 'AdvancedBiomonitorUncommon', 'AdvancedBiomonitorUncommonPlus',
	'AdvancedBionicJointsCommon', 'AdvancedBionicJointsCommon2', 'AdvancedBionicJointsCommon2Plus',
	'AdvancedBionicJointsCommonPlus', 'AdvancedBionicJointsEpic', 'AdvancedBionicJointsEpic2',
	'AdvancedBionicJointsEpic2Plus', 'AdvancedBionicJointsEpicPlus', 'AdvancedBionicJointsLegendary',
	'AdvancedBionicJointsLegendary2', 'AdvancedBionicJointsLegendary2Plus',
	'AdvancedBionicJointsLegendary2PlusPlus', 'AdvancedBionicJointsLegendaryPlus',
	'AdvancedBionicJointsLegendaryPlusPlus', 'AdvancedBionicJointsRare', 'AdvancedBionicJointsRare2',
	'AdvancedBionicJointsRare2Plus', 'AdvancedBionicJointsRarePlus', 'AdvancedBionicJointsStatsShard',
	'AdvancedBionicJointsUncommon', 'AdvancedBionicJointsUncommon2',
	'AdvancedBionicJointsUncommon2Plus', 'AdvancedBionicJointsUncommonPlus',
	'AdvancedBiotechSigmaMKIIIEpic', 'AdvancedBiotechSigmaMKIIIEpicPlus',
	'AdvancedBiotechSigmaMKIIRare', 'AdvancedBiotechSigmaMKIIRarePlus',
	'AdvancedBiotechSigmaMKIUncommon', 'AdvancedBiotechSigmaMKIUncommonPlus',
	'AdvancedBiotechSigmaMKIVLegendary', 'AdvancedBiotechSigmaMKIVLegendaryPlus',
	'AdvancedBiotechSigmaMKIVLegendaryPlusPlus', 'AdvancedBloodDepleterCommon',
	'AdvancedBloodDepleterEpic', 'AdvancedBloodDepleterEpicPlus', 'AdvancedBloodDepleterLegendary',
	'AdvancedBloodDepleterLegendaryPlus', 'AdvancedBloodDepleterLegendaryPlusPlus',
	'AdvancedBloodDepleterRare', 'AdvancedBloodDepleterStatsShard', 'AdvancedBloodDepleterUncommon',
	'AdvancedBloodPumpCommon', 'AdvancedBloodPumpEpic', 'AdvancedBloodPumpEpicPlus',
	'AdvancedBloodPumpLegendary', 'AdvancedBloodPumpLegendaryPlus',
	'AdvancedBloodPumpLegendaryPlusPlus', 'AdvancedBloodPumpRare', 'AdvancedBloodPumpRarePlus',
	'AdvancedBloodPumpStatsShard', 'AdvancedBloodPumpUncommon', 'AdvancedBloodPumpUncommonPlus',
	'AdvancedBoneMarrowCellsCommon', 'AdvancedBoneMarrowCellsCommon2',
	'AdvancedBoneMarrowCellsCommon2Plus', 'AdvancedBoneMarrowCellsCommonPlus',
	'AdvancedBoneMarrowCellsEpic', 'AdvancedBoneMarrowCellsEpic2', 'AdvancedBoneMarrowCellsEpic2Plus',
	'AdvancedBoneMarrowCellsEpicPlus', 'AdvancedBoneMarrowCellsLegendary',
	'AdvancedBoneMarrowCellsLegendary2', 'AdvancedBoneMarrowCellsLegendary2Plus',
	'AdvancedBoneMarrowCellsLegendary2PlusPlus', 'AdvancedBoneMarrowCellsLegendaryPlus',
	'AdvancedBoneMarrowCellsLegendaryPlusPlus', 'AdvancedBoneMarrowCellsRare',
	'AdvancedBoneMarrowCellsRare2', 'AdvancedBoneMarrowCellsRare2Plus',
	'AdvancedBoneMarrowCellsRarePlus', 'AdvancedBoneMarrowCellsStatsShard',
	'AdvancedBoneMarrowCellsUncommon', 'AdvancedBoneMarrowCellsUncommon2',
	'AdvancedBoneMarrowCellsUncommon2Plus', 'AdvancedBoneMarrowCellsUncommonPlus',
	'AdvancedBoostedTendonsEpic', 'AdvancedBoostedTendonsEpicPlus', 'AdvancedBoostedTendonsLegendary',
	'AdvancedBoostedTendonsLegendaryPlus', 'AdvancedBoostedTendonsLegendaryPlusPlus',
	'AdvancedBoostedTendonsRare', 'AdvancedBoostedTendonsRarePlus', 'AdvancedBoostedTendonsStatsShard',
	'AdvancedBoostedTendonsUncommon', 'AdvancedBoostedTendonsUncommonPlus',
	'AdvancedBoringPlatingCommon', 'AdvancedBoringPlatingCommonPlus', 'AdvancedBoringPlatingEpic',
	'AdvancedBoringPlatingEpicPlus', 'AdvancedBoringPlatingLegendary',
	'AdvancedBoringPlatingLegendaryPlus', 'AdvancedBoringPlatingLegendaryPlusPlus',
	'AdvancedBoringPlatingRare', 'AdvancedBoringPlatingRarePlus', 'AdvancedBoringPlatingStatsShard',
	'AdvancedBoringPlatingUncommon', 'AdvancedBoringPlatingUncommonPlus', 'AdvancedBoringPlating_Q001',
	'AdvancedBoringPlating_Tutorial_CommonPlus', 'AdvancedBoringPlating_Tutorial_Epic',
	'AdvancedBoringPlating_Tutorial_EpicPlus', 'AdvancedBoringPlating_Tutorial_Legendary',
	'AdvancedBoringPlating_Tutorial_LegendaryPlus', 'AdvancedBoringPlating_Tutorial_LegendaryPlusPlus',
	'AdvancedBoringPlating_Tutorial_Rare', 'AdvancedBoringPlating_Tutorial_RarePlus',
	'AdvancedBoringPlating_Tutorial_Uncommon', 'AdvancedBoringPlating_Tutorial_UncommonPlus',
	'AdvancedCamilloRamManagerEpic', 'AdvancedCamilloRamManagerEpicPlus',
	'AdvancedCamilloRamManagerLegendary', 'AdvancedCamilloRamManagerLegendaryPlus',
	'AdvancedCamilloRamManagerLegendaryPlusPlus', 'AdvancedCamilloRamManagerStatsShard',
	'AdvancedCardiovascularSystemModule', 'AdvancedCasiusTattoo', 'AdvancedCatPawsEpic',
	'AdvancedCatPawsEpicPlus', 'AdvancedCatPawsLegendary', 'AdvancedCatPawsLegendaryPlus',
	'AdvancedCatPawsLegendaryPlusPlus', 'AdvancedCatPawsRare', 'AdvancedCatPawsRarePlus',
	'AdvancedCatPawsStatsShard', 'AdvancedCatPawsUncommon', 'AdvancedCatPawsUncommonPlus',
	'AdvancedCatchMeIfYouCanCommon', 'AdvancedCatchMeIfYouCanCommonPlus',
	'AdvancedCatchMeIfYouCanEpic', 'AdvancedCatchMeIfYouCanEpicPlus',
	'AdvancedCatchMeIfYouCanLegendary', 'AdvancedCatchMeIfYouCanLegendaryPlus',
	'AdvancedCatchMeIfYouCanLegendaryPlusPlus', 'AdvancedCatchMeIfYouCanRare',
	'AdvancedCatchMeIfYouCanRarePlus', 'AdvancedCatchMeIfYouCanStatsShard',
	'AdvancedCatchMeIfYouCanUncommon', 'AdvancedCatchMeIfYouCanUncommonPlus',
	'AdvancedChargeSystemCommon', 'AdvancedChargeSystemCommonPlus', 'AdvancedChargeSystemEpic',
	'AdvancedChargeSystemEpicPlus', 'AdvancedChargeSystemLegendary',
	'AdvancedChargeSystemLegendaryPlus', 'AdvancedChargeSystemLegendaryPlusPlus',
	'AdvancedChargeSystemRare', 'AdvancedChargeSystemRarePlus', 'AdvancedChargeSystemStatsShard',
	'AdvancedChargeSystemUncommon', 'AdvancedChargeSystemUncommonPlus', 'AdvancedChargeSystem_Q001',
	'AdvancedChitonStatsShard', 'AdvancedCogitoFrameCommon', 'AdvancedCogitoFrameCommonPlus',
	'AdvancedCogitoFrameEpic', 'AdvancedCogitoFrameEpicPlus', 'AdvancedCogitoFrameLegendary',
	'AdvancedCogitoFrameLegendaryPlus', 'AdvancedCogitoFrameLegendaryPlusPlus',
	'AdvancedCogitoFrameRare', 'AdvancedCogitoFrameRarePlus', 'AdvancedCogitoFrameStatsShard',
	'AdvancedCogitoFrameUncommon', 'AdvancedCogitoFrameUncommonPlus', 'AdvancedCommonDeck',
	'AdvancedCompilingSkeletonCommon', 'AdvancedCompilingSkeletonCommon2',
	'AdvancedCompilingSkeletonCommon2Plus', 'AdvancedCompilingSkeletonCommonPlus',
	'AdvancedCompilingSkeletonEpic', 'AdvancedCompilingSkeletonEpic2',
	'AdvancedCompilingSkeletonEpic2Plus', 'AdvancedCompilingSkeletonEpicPlus',
	'AdvancedCompilingSkeletonLegendary', 'AdvancedCompilingSkeletonLegendary2',
	'AdvancedCompilingSkeletonLegendary2Plus', 'AdvancedCompilingSkeletonLegendary2PlusPlus',
	'AdvancedCompilingSkeletonLegendaryPlus', 'AdvancedCompilingSkeletonLegendaryPlusPlus',
	'AdvancedCompilingSkeletonRare', 'AdvancedCompilingSkeletonRare2',
	'AdvancedCompilingSkeletonRare2Plus', 'AdvancedCompilingSkeletonRarePlus',
	'AdvancedCompilingSkeletonStatsShard', 'AdvancedCompilingSkeletonUncommon',
	'AdvancedCompilingSkeletonUncommon2', 'AdvancedCompilingSkeletonUncommon2Plus',
	'AdvancedCompilingSkeletonUncommonPlus', 'AdvancedCyberRotorsCommon',
	'AdvancedCyberRotorsCommonPlus', 'AdvancedCyberRotorsEpic', 'AdvancedCyberRotorsEpicPlus',
	'AdvancedCyberRotorsLegendary', 'AdvancedCyberRotorsLegendaryPlus',
	'AdvancedCyberRotorsLegendaryPlusPlus', 'AdvancedCyberRotorsRare', 'AdvancedCyberRotorsRarePlus',
	'AdvancedCyberRotorsStatsShard', 'AdvancedCyberRotorsUncommon', 'AdvancedCyberRotorsUncommonPlus',
	'AdvancedDenseMarrowBase', 'AdvancedDenseMarrowCommon', 'AdvancedDenseMarrowCommon2',
	'AdvancedDenseMarrowCommon2Plus', 'AdvancedDenseMarrowCommonPlus', 'AdvancedDenseMarrowEpic',
	'AdvancedDenseMarrowEpic2', 'AdvancedDenseMarrowEpic2Plus', 'AdvancedDenseMarrowEpicPlus',
	'AdvancedDenseMarrowLegendary', 'AdvancedDenseMarrowLegendary2',
	'AdvancedDenseMarrowLegendary2Plus', 'AdvancedDenseMarrowLegendary2PlusPlus',
	'AdvancedDenseMarrowLegendaryPlus', 'AdvancedDenseMarrowLegendaryPlusPlus',
	'AdvancedDenseMarrowRare', 'AdvancedDenseMarrowRare2', 'AdvancedDenseMarrowRare2Plus',
	'AdvancedDenseMarrowRarePlus', 'AdvancedDenseMarrowStatsShard', 'AdvancedDenseMarrowUncommon',
	'AdvancedDenseMarrowUncommon2', 'AdvancedDenseMarrowUncommon2Plus',
	'AdvancedDenseMarrowUncommonPlus', 'AdvancedDetectorRushCommon', 'AdvancedDetectorRushCommonPlus',
	'AdvancedDetectorRushEpic', 'AdvancedDetectorRushEpicPlus', 'AdvancedDetectorRushLegendary',
	'AdvancedDetectorRushLegendaryPlus', 'AdvancedDetectorRushLegendaryPlusPlus',
	'AdvancedDetectorRushRare', 'AdvancedDetectorRushRarePlus', 'AdvancedDetectorRushStatsShard',
	'AdvancedDetectorRushUncommon', 'AdvancedDetectorRushUncommonPlus',
	'AdvancedDischargeConnectorEpic', 'AdvancedDischargeConnectorEpicPlus',
	'AdvancedDischargeConnectorLegendary', 'AdvancedDischargeConnectorLegendaryPlus',
	'AdvancedDischargeConnectorLegendaryPlusPlus', 'AdvancedDischargeConnectorRare',
	'AdvancedDischargeConnectorRarePlus', 'AdvancedDischargeConnectorStatsShard',
	'AdvancedElectroshockMechanismCommon', 'AdvancedElectroshockMechanismCommonPlus',
	'AdvancedElectroshockMechanismEpic', 'AdvancedElectroshockMechanismEpicPlus',
	'AdvancedElectroshockMechanismLegendary', 'AdvancedElectroshockMechanismLegendaryPlus',
	'AdvancedElectroshockMechanismLegendaryPlusPlus', 'AdvancedElectroshockMechanismRare',
	'AdvancedElectroshockMechanismRarePlus', 'AdvancedElectroshockMechanismStatsShard',
	'AdvancedElectroshockMechanismUncommon', 'AdvancedElectroshockMechanismUncommonPlus',
	'AdvancedEndoSkeletonLegendary2', 'AdvancedEndoSkeletonLegendary2Plus',
	'AdvancedEndoSkeletonLegendary2PlusPlus', 'AdvancedEndoskeletonEpic', 'AdvancedEndoskeletonEpic2',
	'AdvancedEndoskeletonEpic2Plus', 'AdvancedEndoskeletonEpicPlus', 'AdvancedEndoskeletonLegendary',
	'AdvancedEndoskeletonLegendaryPlus', 'AdvancedEndoskeletonLegendaryPlusPlus',
	'AdvancedEndoskeletonStatsShard', 'AdvancedEpicDeck', 'AdvancedEpicHighEnergyDeck',
	'AdvancedEpicLowEnergyDeck', 'AdvancedEpicMidEnergyDeck', 'AdvancedExDiskEpic',
	'AdvancedExDiskEpicPlus', 'AdvancedExDiskLegendary', 'AdvancedExDiskLegendaryPlus',
	'AdvancedExDiskLegendaryPlusPlus', 'AdvancedExDiskRare', 'AdvancedExDiskRarePlus',
	'AdvancedExDiskStatsShard', 'AdvancedFrontalCortexModule', 'AdvancedHandsModule',
	'AdvancedHealOnKillCommon', 'AdvancedHealOnKillCommonPlus', 'AdvancedHealOnKillEpic',
	'AdvancedHealOnKillEpicPlus', 'AdvancedHealOnKillLegendary', 'AdvancedHealOnKillLegendaryPlus',
	'AdvancedHealOnKillLegendaryPlusPlus', 'AdvancedHealOnKillRare', 'AdvancedHealOnKillRarePlus',
	'AdvancedHealOnKillStatsShard', 'AdvancedHealOnKillUncommon', 'AdvancedHealOnKillUncommonPlus',
	'AdvancedImmuneSystemModule', 'AdvancedIntegumentarySystemModule', 'AdvancedJenkinsTendonsCommon',
	'AdvancedJenkinsTendonsCommonPlus', 'AdvancedJenkinsTendonsEpic', 'AdvancedJenkinsTendonsEpicPlus',
	'AdvancedJenkinsTendonsLegendary', 'AdvancedJenkinsTendonsLegendaryPlus',
	'AdvancedJenkinsTendonsLegendaryPlusPlus', 'AdvancedJenkinsTendonsRare',
	'AdvancedJenkinsTendonsRarePlus', 'AdvancedJenkinsTendonsStatsShard',
	'AdvancedJenkinsTendonsUncommon', 'AdvancedJenkinsTendonsUncommonPlus', 'AdvancedJointLockCommon',
	'AdvancedJointLockCommonPlus', 'AdvancedJointLockEpic', 'AdvancedJointLockEpicPlus',
	'AdvancedJointLockLegendary', 'AdvancedJointLockLegendaryPlus',
	'AdvancedJointLockLegendaryPlusPlus', 'AdvancedJointLockRare', 'AdvancedJointLockRarePlus',
	'AdvancedJointLockStatsShard', 'AdvancedJointLockUncommon', 'AdvancedJointLockUncommonPlus',
	'AdvancedKerenzikovCommon', 'AdvancedKerenzikovEpic', 'AdvancedKerenzikovEpicPlus',
	'AdvancedKerenzikovLegendary', 'AdvancedKerenzikovLegendaryPlus',
	'AdvancedKerenzikovLegendaryPlusPlus', 'AdvancedKerenzikovRare', 'AdvancedKerenzikovRarePlus',
	'AdvancedKerenzikovStatsShard', 'AdvancedKerenzikovUncommon', 'AdvancedKerenzikovUncommonPlus',
	'AdvancedKerenziovBoostSystemCommon', 'AdvancedKerenziovBoostSystemCommonPlus',
	'AdvancedKerenziovBoostSystemEpic', 'AdvancedKerenziovBoostSystemEpicPlus',
	'AdvancedKerenziovBoostSystemLegendary', 'AdvancedKerenziovBoostSystemLegendaryPlus',
	'AdvancedKerenziovBoostSystemLegendaryPlusPlus', 'AdvancedKerenziovBoostSystemRare',
	'AdvancedKerenziovBoostSystemRarePlus', 'AdvancedKerenziovBoostSystemStatsShard',
	'AdvancedKerenziovBoostSystemUncommon', 'AdvancedKiroshiOptics', 'AdvancedKiroshiOpticsBareBase',
	'AdvancedKiroshiOpticsBareCommon', 'AdvancedKiroshiOpticsBareCommonPlus',
	'AdvancedKiroshiOpticsBareEpic', 'AdvancedKiroshiOpticsBareEpicPlus',
	'AdvancedKiroshiOpticsBareLegendary', 'AdvancedKiroshiOpticsBareLegendaryPlus',
	'AdvancedKiroshiOpticsBareLegendaryPlusPlus', 'AdvancedKiroshiOpticsBareRare',
	'AdvancedKiroshiOpticsBareRarePlus', 'AdvancedKiroshiOpticsBareStatsShard',
	'AdvancedKiroshiOpticsBareUncommon', 'AdvancedKiroshiOpticsBareUncommonPlus',
	'AdvancedKiroshiOpticsCombinedBase', 'AdvancedKiroshiOpticsCombinedCommon',
	'AdvancedKiroshiOpticsCombinedCommonPlus', 'AdvancedKiroshiOpticsCombinedEpic',
	'AdvancedKiroshiOpticsCombinedEpicPlus', 'AdvancedKiroshiOpticsCombinedLegendary',
	'AdvancedKiroshiOpticsCombinedLegendaryPlus', 'AdvancedKiroshiOpticsCombinedLegendaryPlusPlus',
	'AdvancedKiroshiOpticsCombinedRare', 'AdvancedKiroshiOpticsCombinedRarePlus',
	'AdvancedKiroshiOpticsCombinedStatsShard', 'AdvancedKiroshiOpticsCombinedUncommon',
	'AdvancedKiroshiOpticsCombinedUncommonPlus', 'AdvancedKiroshiOpticsEpic',
	'AdvancedKiroshiOpticsHunterBase', 'AdvancedKiroshiOpticsHunterCommon',
	'AdvancedKiroshiOpticsHunterCommonPlus', 'AdvancedKiroshiOpticsHunterEpic',
	'AdvancedKiroshiOpticsHunterEpicPlus', 'AdvancedKiroshiOpticsHunterLegendary',
	'AdvancedKiroshiOpticsHunterLegendaryPlus', 'AdvancedKiroshiOpticsHunterLegendaryPlusPlus',
	'AdvancedKiroshiOpticsHunterRare', 'AdvancedKiroshiOpticsHunterRarePlus',
	'AdvancedKiroshiOpticsHunterStatsShard', 'AdvancedKiroshiOpticsHunterUncommon',
	'AdvancedKiroshiOpticsHunterUncommonPlus', 'AdvancedKiroshiOpticsLegendary',
	'AdvancedKiroshiOpticsPiercingBase', 'AdvancedKiroshiOpticsPiercingCommon',
	'AdvancedKiroshiOpticsPiercingCommonPlus', 'AdvancedKiroshiOpticsPiercingEpic',
	'AdvancedKiroshiOpticsPiercingEpicPlus', 'AdvancedKiroshiOpticsPiercingLegendary',
	'AdvancedKiroshiOpticsPiercingLegendaryPlus', 'AdvancedKiroshiOpticsPiercingLegendaryPlusPlus',
	'AdvancedKiroshiOpticsPiercingRare', 'AdvancedKiroshiOpticsPiercingRarePlus',
	'AdvancedKiroshiOpticsPiercingStatsShard', 'AdvancedKiroshiOpticsPiercingUncommon',
	'AdvancedKiroshiOpticsPiercingUncommonPlus', 'AdvancedKiroshiOpticsPlus',
	'AdvancedKiroshiOpticsRare', 'AdvancedKiroshiOpticsSensorBase',
	'AdvancedKiroshiOpticsSensorCommon', 'AdvancedKiroshiOpticsSensorCommonPlus',
	'AdvancedKiroshiOpticsSensorEpic', 'AdvancedKiroshiOpticsSensorEpicPlus',
	'AdvancedKiroshiOpticsSensorLegendary', 'AdvancedKiroshiOpticsSensorLegendaryPlus',
	'AdvancedKiroshiOpticsSensorLegendaryPlusPlus', 'AdvancedKiroshiOpticsSensorRare',
	'AdvancedKiroshiOpticsSensorRarePlus', 'AdvancedKiroshiOpticsSensorStatsShard',
	'AdvancedKiroshiOpticsSensorUncommonPlus', 'AdvancedKiroshiOpticsSensor_Uncommon',
	'AdvancedKiroshiOpticsStatsShard', 'AdvancedKiroshiOpticsUncommon',
	'AdvancedKiroshiOpticsWallhackBase', 'AdvancedKiroshiOpticsWallhackCommon',
	'AdvancedKiroshiOpticsWallhackCommonPlus', 'AdvancedKiroshiOpticsWallhackEpic',
	'AdvancedKiroshiOpticsWallhackEpicPlus', 'AdvancedKiroshiOpticsWallhackLegendary',
	'AdvancedKiroshiOpticsWallhackLegendaryPlus', 'AdvancedKiroshiOpticsWallhackLegendaryPlusPlus',
	'AdvancedKiroshiOpticsWallhackRare', 'AdvancedKiroshiOpticsWallhackRarePlus',
	'AdvancedKiroshiOpticsWallhackStatsShard', 'AdvancedKiroshiOpticsWallhackUncommon',
	'AdvancedKiroshiOpticsWallhackUncommonPlus', 'AdvancedKiroshiOptics_Tutorial_CommonPlus',
	'AdvancedKiroshiOptics_Tutorial_Epic', 'AdvancedKiroshiOptics_Tutorial_EpicPlus',
	'AdvancedKiroshiOptics_Tutorial_Legendary', 'AdvancedKiroshiOptics_Tutorial_LegendaryPlus',
	'AdvancedKiroshiOptics_Tutorial_LegendaryPlusPlus', 'AdvancedKiroshiOptics_Tutorial_Rare',
	'AdvancedKiroshiOptics_Tutorial_RarePlus', 'AdvancedKiroshiOptics_Tutorial_Uncommon',
	'AdvancedKiroshiOptics_Tutorial_UncommonPlus', 'AdvancedKiroshiOptics_q001_1',
	'AdvancedKiroshiOptics_q001_2', 'AdvancedKiroshiOptics_q001_3', 'AdvancedKnifeSharpenerCommon',
	'AdvancedKnifeSharpenerEpic', 'AdvancedKnifeSharpenerEpicPlus', 'AdvancedKnifeSharpenerLegendary',
	'AdvancedKnifeSharpenerLegendaryPlus', 'AdvancedKnifeSharpenerLegendaryPlusPlus',
	'AdvancedKnifeSharpenerRare', 'AdvancedKnifeSharpenerRarePlus', 'AdvancedKnifeSharpenerStatsShard',
	'AdvancedKnifeSharpenerUncommon', 'AdvancedLegendaryDeck', 'AdvancedLegendaryHighEnergyDeck',
	'AdvancedLegendaryLowEnergyDeck', 'AdvancedLegendaryMidEnergyDeck',
	'AdvancedLegendaryVeryHighEnergyDeck', 'AdvancedLegsModule', 'AdvancedMantisBladesBase',
	'AdvancedMantisBladesChemicalEpic', 'AdvancedMantisBladesChemicalEpicPlus',
	'AdvancedMantisBladesChemicalLegendary', 'AdvancedMantisBladesChemicalLegendaryPlus',
	'AdvancedMantisBladesChemicalLegendaryPlusPlus', 'AdvancedMantisBladesChemicalRare',
	'AdvancedMantisBladesChemicalRarePlus', 'AdvancedMantisBladesChemicalStatsShard',
	'AdvancedMantisBladesChemicalUncommon', 'AdvancedMantisBladesChemicalUncommonPlus',
	'AdvancedMantisBladesElectricEpic', 'AdvancedMantisBladesElectricEpicPlus',
	'AdvancedMantisBladesElectricLegendary', 'AdvancedMantisBladesElectricLegendaryPlus',
	'AdvancedMantisBladesElectricLegendaryPlusPlus', 'AdvancedMantisBladesElectricRare',
	'AdvancedMantisBladesElectricRarePlus', 'AdvancedMantisBladesElectricStatsShard',
	'AdvancedMantisBladesElectricUncommon', 'AdvancedMantisBladesElectricUncommonPlus',
	'AdvancedMantisBladesEpic', 'AdvancedMantisBladesEpicPlus', 'AdvancedMantisBladesLegendary',
	'AdvancedMantisBladesLegendaryPlus', 'AdvancedMantisBladesLegendaryPlusPlus',
	'AdvancedMantisBladesRare', 'AdvancedMantisBladesRarePlus', 'AdvancedMantisBladesStatsShard',
	'AdvancedMantisBladesThermalEpic', 'AdvancedMantisBladesThermalEpicPlus',
	'AdvancedMantisBladesThermalLegendary', 'AdvancedMantisBladesThermalLegendaryPlus',
	'AdvancedMantisBladesThermalLegendaryPlusPlus', 'AdvancedMantisBladesThermalRare',
	'AdvancedMantisBladesThermalRarePlus', 'AdvancedMantisBladesThermalStatsShard',
	'AdvancedMantisBladesThermalUncommon', 'AdvancedMantisBladesThermalUncommonPlus',
	'AdvancedMantisBladesUncommon', 'AdvancedMantisBladesUncommonPlus',
	'AdvancedMaxTacMantisBladesEpic', 'AdvancedMaxTacMantisBladesEpicPlus',
	'AdvancedMaxTacMantisBladesLegendary', 'AdvancedMaxTacMantisBladesLegendaryPlus',
	'AdvancedMaxTacMantisBladesLegendaryPlusPlus', 'AdvancedMaxTacMantisBladesStatsShard',
	'AdvancedMechatronicCoreCommon', 'AdvancedMechatronicCoreCommonPlus',
	'AdvancedMechatronicCoreEpic', 'AdvancedMechatronicCoreEpicPlus',
	'AdvancedMechatronicCoreLegendary', 'AdvancedMechatronicCoreLegendaryPlus',
	'AdvancedMechatronicCoreLegendaryPlusPlus', 'AdvancedMechatronicCoreRare',
	'AdvancedMechatronicCoreRarePlus', 'AdvancedMechatronicCoreStatsShard',
	'AdvancedMechatronicCoreUncommon', 'AdvancedMechatronicCoreUncommonPlus',
	'AdvancedMemoryBoostEpic', 'AdvancedMemoryBoostEpicPlus', 'AdvancedMemoryBoostLegendary',
	'AdvancedMemoryBoostLegendaryPlus', 'AdvancedMemoryBoostLegendaryPlusPlus',
	'AdvancedMemoryBoostRare', 'AdvancedMemoryBoostRarePlus', 'AdvancedMemoryBoostStatsShard',
	'AdvancedMemoryBoostUncommon', 'AdvancedMemoryBoostUncommonPlus', 'AdvancedMicroGeneratorCommon',
	'AdvancedMicroGeneratorEpic', 'AdvancedMicroGeneratorEpicPlus', 'AdvancedMicroGeneratorLegendary',
	'AdvancedMicroGeneratorLegendaryPlus', 'AdvancedMicroGeneratorLegendaryPlusPlus',
	'AdvancedMicroGeneratorRare', 'AdvancedMicroGeneratorRarePlus', 'AdvancedMicroGeneratorStatsShard',
	'AdvancedMicroGeneratorUncommon', 'AdvancedMicroGeneratorUncommonPlus',
	'AdvancedMilitechParalineMKICommon', 'AdvancedMilitechParalineMKICommonPlus',
	'AdvancedMilitechParalineMKIIIRare', 'AdvancedMilitechParalineMKIIIRarePlus',
	'AdvancedMilitechParalineMKIIUncommon', 'AdvancedMilitechParalineMKIIUncommonPlus',
	'AdvancedMilitechParalineMKIVEpic', 'AdvancedMilitechParalineMKIVEpicPlus',
	'AdvancedMilitechParalineMKVLegendary', 'AdvancedMilitechParalineMKVLegendaryPlus',
	'AdvancedMilitechParalineMKVLegendaryPlusPlus', 'AdvancedMusculoskeletalSystemModule',
	'AdvancedNanoTechPlatesCommon', 'AdvancedNanoTechPlatesEpic', 'AdvancedNanoTechPlatesEpicPlus',
	'AdvancedNanoTechPlatesLegendary', 'AdvancedNanoTechPlatesLegendaryPlus',
	'AdvancedNanoTechPlatesLegendaryPlusPlus', 'AdvancedNanoTechPlatesRare',
	'AdvancedNanoTechPlatesRarePlus', 'AdvancedNanoTechPlatesStatsShard',
	'AdvancedNanoTechPlatesUncommon', 'AdvancedNanoTechPlatesUncommonPlus', 'AdvancedNanoWiresBase',
	'AdvancedNanoWiresChemicalEpic', 'AdvancedNanoWiresChemicalEpicPlus',
	'AdvancedNanoWiresChemicalLegendary', 'AdvancedNanoWiresChemicalLegendaryPlus',
	'AdvancedNanoWiresChemicalLegendaryPlusPlus', 'AdvancedNanoWiresChemicalRare',
	'AdvancedNanoWiresChemicalRarePlus', 'AdvancedNanoWiresChemicalStatsShard',
	'AdvancedNanoWiresChemicalUncommon', 'AdvancedNanoWiresChemicalUncommonPlus',
	'AdvancedNanoWiresElectricEpic', 'AdvancedNanoWiresElectricEpicPlus',
	'AdvancedNanoWiresElectricLegendary', 'AdvancedNanoWiresElectricLegendaryPlus',
	'AdvancedNanoWiresElectricLegendaryPlusPlus', 'AdvancedNanoWiresElectricRare',
	'AdvancedNanoWiresElectricRarePlus', 'AdvancedNanoWiresElectricStatsShard',
	'AdvancedNanoWiresElectricUncommon', 'AdvancedNanoWiresElectricUncommonPlus',
	'AdvancedNanoWiresEpic', 'AdvancedNanoWiresEpicPlus', 'AdvancedNanoWiresLegendary',
	'AdvancedNanoWiresLegendaryPlus', 'AdvancedNanoWiresLegendaryPlusPlus', 'AdvancedNanoWiresRare',
	'AdvancedNanoWiresRarePlus', 'AdvancedNanoWiresStatsShard', 'AdvancedNanoWiresThermalEpic',
	'AdvancedNanoWiresThermalEpicPlus', 'AdvancedNanoWiresThermalLegendary',
	'AdvancedNanoWiresThermalLegendaryPlus', 'AdvancedNanoWiresThermalLegendaryPlusPlus',
	'AdvancedNanoWiresThermalRare', 'AdvancedNanoWiresThermalRarePlus',
	'AdvancedNanoWiresThermalStatsShard', 'AdvancedNanoWiresThermalUncommon',
	'AdvancedNanoWiresThermalUncommonPlus', 'AdvancedNanoWiresUncommon',
	'AdvancedNanoWiresUncommonPlus', 'AdvancedNeoFiberCommon', 'AdvancedNeoFiberEpic',
	'AdvancedNeoFiberEpicPlus', 'AdvancedNeoFiberLegendary', 'AdvancedNeoFiberLegendaryPlus',
	'AdvancedNeoFiberLegendaryPlusPlus', 'AdvancedNeoFiberRare', 'AdvancedNeoFiberRarePlus',
	'AdvancedNeoFiberStatsShard', 'AdvancedNeoFiberUncommon', 'AdvancedNervousSystemModule',
	'AdvancedNetwatchNetdriverMKLegendary', 'AdvancedNetwatchNetdriverMKLegendaryPlus',
	'AdvancedNetwatchNetdriverMKLegendaryPlusPlus', 'AdvancedNeuroMatrixCommon',
	'AdvancedNeuroMatrixCommon2', 'AdvancedNeuroMatrixCommon2Plus', 'AdvancedNeuroMatrixCommonPlus',
	'AdvancedNeuroMatrixEpic', 'AdvancedNeuroMatrixEpic2', 'AdvancedNeuroMatrixEpic2Plus',
	'AdvancedNeuroMatrixEpicPlus', 'AdvancedNeuroMatrixLegendary', 'AdvancedNeuroMatrixLegendary2',
	'AdvancedNeuroMatrixLegendary2Plus', 'AdvancedNeuroMatrixLegendary2PlusPlus',
	'AdvancedNeuroMatrixLegendaryPlus', 'AdvancedNeuroMatrixLegendaryPlusPlus',
	'AdvancedNeuroMatrixRare', 'AdvancedNeuroMatrixRare2', 'AdvancedNeuroMatrixRare2Plus',
	'AdvancedNeuroMatrixRarePlus', 'AdvancedNeuroMatrixStatsShard', 'AdvancedNeuroMatrixUncommon',
	'AdvancedNeuroMatrixUncommon2', 'AdvancedNeuroMatrixUncommon2Plus',
	'AdvancedNeuroMatrixUncommonPlus', 'AdvancedNoPainNoGainCommon', 'AdvancedNoPainNoGainCommon2',
	'AdvancedNoPainNoGainCommon2Plus', 'AdvancedNoPainNoGainCommonPlus', 'AdvancedNoPainNoGainEpic',
	'AdvancedNoPainNoGainEpic2', 'AdvancedNoPainNoGainEpic2Plus', 'AdvancedNoPainNoGainEpicPlus',
	'AdvancedNoPainNoGainLegendary2', 'AdvancedNoPainNoGainLegendary2Plus',
	'AdvancedNoPainNoGainLegendary2PlusPlus', 'AdvancedNoPainNoGainLegendaryPlus',
	'AdvancedNoPainNoGainLegendaryPlusPlus', 'AdvancedNoPainNoGainRare', 'AdvancedNoPainNoGainRare2',
	'AdvancedNoPainNoGainRare2Plus', 'AdvancedNoPainNoGainRarePlus', 'AdvancedNoPainNoGainStatsShard',
	'AdvancedNoPainNoGainUncommon', 'AdvancedNoPainNoGainUncommon2',
	'AdvancedNoPainNoGainUncommon2Plus', 'AdvancedNoPainNoGainUncommonPlus',
	'AdvancedNoPainNoGain_Legendary', 'AdvancedOilDispenserCommon', 'AdvancedOilDispenserCommonPlus',
	'AdvancedOilDispenserEpic', 'AdvancedOilDispenserEpicPlus', 'AdvancedOilDispenserLegendary',
	'AdvancedOilDispenserLegendaryPlus', 'AdvancedOilDispenserLegendaryPlusPlus',
	'AdvancedOilDispenserRare', 'AdvancedOilDispenserRarePlus', 'AdvancedOilDispenserStatsShard',
	'AdvancedOilDispenserUncommon', 'AdvancedOilDispenserUncommonPlus', 'AdvancedOpticalCamoCommon',
	'AdvancedOpticalCamoEpic', 'AdvancedOpticalCamoEpicPlus', 'AdvancedOpticalCamoLegendary',
	'AdvancedOpticalCamoLegendaryPlus', 'AdvancedOpticalCamoLegendaryPlusPlus',
	'AdvancedOpticalCamoRare', 'AdvancedOpticalCamoRarePlus', 'AdvancedOpticalCamoStatsShard',
	'AdvancedOpticalCamoUncommon', 'AdvancedOpticalCamoUncommonPlus', 'AdvancedPainDistributorCommon',
	'AdvancedPainDistributorCommon2', 'AdvancedPainDistributorEpic', 'AdvancedPainDistributorEpic2',
	'AdvancedPainDistributorEpic2Plus', 'AdvancedPainDistributorEpicPlus',
	'AdvancedPainDistributorLegendary', 'AdvancedPainDistributorLegendary2',
	'AdvancedPainDistributorLegendary2Plus', 'AdvancedPainDistributorLegendary2PlusPlus',
	'AdvancedPainDistributorLegendaryPlus', 'AdvancedPainDistributorLegendaryPlusPlus',
	'AdvancedPainDistributorRare', 'AdvancedPainDistributorRare2', 'AdvancedPainDistributorRare2Plus',
	'AdvancedPainDistributorRarePlus', 'AdvancedPainDistributorStatsShard',
	'AdvancedPainDistributorUncommon', 'AdvancedPainDistributorUncommon2', 'AdvancedPainReductorEpic',
	'AdvancedPainReductorEpicPlus', 'AdvancedPainReductorLegendary',
	'AdvancedPainReductorLegendaryPlus', 'AdvancedPainReductorLegendaryPlusPlus',
	'AdvancedPainReductorStatsShard', 'AdvancedPlatingGlitchCommon', 'AdvancedPlatingGlitchEpic',
	'AdvancedPlatingGlitchEpicPlus', 'AdvancedPlatingGlitchLegendary',
	'AdvancedPlatingGlitchLegendaryPlus', 'AdvancedPlatingGlitchLegendaryPlusPlus',
	'AdvancedPlatingGlitchRare', 'AdvancedPlatingGlitchRarePlus', 'AdvancedPlatingGlitchStatsShard',
	'AdvancedPlatingGlitchUncommon', 'AdvancedPowerGripCommon', 'AdvancedPowerGripCommonPlus',
	'AdvancedPowerGripEpic', 'AdvancedPowerGripEpicPlus', 'AdvancedPowerGripLegendary',
	'AdvancedPowerGripLegendaryPlus', 'AdvancedPowerGripLegendaryPlusPlus', 'AdvancedPowerGripRare',
	'AdvancedPowerGripRarePlus', 'AdvancedPowerGripStatsShard', 'AdvancedPowerGripUncommon',
	'AdvancedPowerGripUncommonPlus', 'AdvancedPowerGrip_Tutorial_CommonPlus',
	'AdvancedPowerGrip_Tutorial_Epic', 'AdvancedPowerGrip_Tutorial_EpicPlus',
	'AdvancedPowerGrip_Tutorial_Legendary', 'AdvancedPowerGrip_Tutorial_LegendaryPlus',
	'AdvancedPowerGrip_Tutorial_LegendaryPlusPlus', 'AdvancedPowerGrip_Tutorial_Rare',
	'AdvancedPowerGrip_Tutorial_RarePlus', 'AdvancedPowerGrip_Tutorial_Uncommon',
	'AdvancedPowerGrip_Tutorial_UncommonPlus', 'AdvancedPowerGrip_q001_1', 'AdvancedPowerGrip_q001_2',
	'AdvancedPowerGrip_q001_3', 'AdvancedProjectileLauncherBase',
	'AdvancedProjectileLauncherChemicalEpic', 'AdvancedProjectileLauncherChemicalEpicPlus',
	'AdvancedProjectileLauncherChemicalLegendary', 'AdvancedProjectileLauncherChemicalLegendaryPlus',
	'AdvancedProjectileLauncherChemicalLegendaryPlusPlus', 'AdvancedProjectileLauncherChemicalRare',
	'AdvancedProjectileLauncherChemicalRarePlus', 'AdvancedProjectileLauncherChemicalStatsShard',
	'AdvancedProjectileLauncherChemicalUncommon', 'AdvancedProjectileLauncherChemicalUncommonPlus',
	'AdvancedProjectileLauncherElectricEpic', 'AdvancedProjectileLauncherElectricEpicPlus',
	'AdvancedProjectileLauncherElectricLegendary', 'AdvancedProjectileLauncherElectricLegendaryPlus',
	'AdvancedProjectileLauncherElectricLegendaryPlusPlus', 'AdvancedProjectileLauncherElectricRare',
	'AdvancedProjectileLauncherElectricRarePlus', 'AdvancedProjectileLauncherElectricStatsShard',
	'AdvancedProjectileLauncherElectricUncommon', 'AdvancedProjectileLauncherElectricUncommonPlus',
	'AdvancedProjectileLauncherEpic', 'AdvancedProjectileLauncherEpicPlus',
	'AdvancedProjectileLauncherLegendary', 'AdvancedProjectileLauncherLegendaryPlus',
	'AdvancedProjectileLauncherLegendaryPlusPlus', 'AdvancedProjectileLauncherRare',
	'AdvancedProjectileLauncherRarePlus', 'AdvancedProjectileLauncherStatsShard',
	'AdvancedProjectileLauncherThermalEpic', 'AdvancedProjectileLauncherThermalEpicPlus',
	'AdvancedProjectileLauncherThermalLegendary', 'AdvancedProjectileLauncherThermalLegendaryPlus',
	'AdvancedProjectileLauncherThermalLegendaryPlusPlus', 'AdvancedProjectileLauncherThermalRare',
	'AdvancedProjectileLauncherThermalRarePlus', 'AdvancedProjectileLauncherThermalStatsShard',
	'AdvancedProjectileLauncherThermalUncommon', 'AdvancedProjectileLauncherThermalUncommonPlus',
	'AdvancedProjectileLauncherUncommon', 'AdvancedProjectileLauncherUncommonPlus',
	'AdvancedProximityReducerCommon', 'AdvancedProximityReducerCommonPlus',
	'AdvancedProximityReducerEpic', 'AdvancedProximityReducerEpicPlus',
	'AdvancedProximityReducerLegendary', 'AdvancedProximityReducerLegendaryPlus',
	'AdvancedProximityReducerLegendaryPlusPlus', 'AdvancedProximityReducerRare',
	'AdvancedProximityReducerRarePlus', 'AdvancedProximityReducerStatsShard',
	'AdvancedProximityReducerUncommon', 'AdvancedProximityReducerUncommonPlus',
	'AdvancedProximityReducer_Q001', 'AdvancedRamUpgradeCommon', 'AdvancedRamUpgradeCommonPlus',
	'AdvancedRamUpgradeEpic', 'AdvancedRamUpgradeEpicPlus', 'AdvancedRamUpgradeLegendary',
	'AdvancedRamUpgradeLegendaryPlus', 'AdvancedRamUpgradeLegendaryPlusPlus', 'AdvancedRamUpgradeRare',
	'AdvancedRamUpgradeRarePlus', 'AdvancedRamUpgradeStatsShard', 'AdvancedRamUpgradeUncommon',
	'AdvancedRamUpgradeUncommonPlus', 'AdvancedRapidMuscleNurishCommon',
	'AdvancedRapidMuscleNurishCommon2', 'AdvancedRapidMuscleNurishCommon2Plus',
	'AdvancedRapidMuscleNurishCommonPlus', 'AdvancedRapidMuscleNurishEpic',
	'AdvancedRapidMuscleNurishEpic2', 'AdvancedRapidMuscleNurishEpic2Plus',
	'AdvancedRapidMuscleNurishEpicPlus', 'AdvancedRapidMuscleNurishLegendary',
	'AdvancedRapidMuscleNurishLegendary2', 'AdvancedRapidMuscleNurishLegendary2Plus',
	'AdvancedRapidMuscleNurishLegendary2PlusPlus', 'AdvancedRapidMuscleNurishLegendaryPlus',
	'AdvancedRapidMuscleNurishLegendaryPlusPlus', 'AdvancedRapidMuscleNurishRare',
	'AdvancedRapidMuscleNurishRare2', 'AdvancedRapidMuscleNurishRare2Plus',
	'AdvancedRapidMuscleNurishRarePlus', 'AdvancedRapidMuscleNurishStatsShard',
	'AdvancedRapidMuscleNurishUncommon', 'AdvancedRapidMuscleNurishUncommon2',
	'AdvancedRapidMuscleNurishUncommon2Plus', 'AdvancedRapidMuscleNurishUncommonPlus',
	'AdvancedRareDeck', 'AdvancedRareHighEnergyDeck', 'AdvancedRareLowEnergyDeck',
	'AdvancedRareMidEnergyDeck', 'AdvancedRavenMicrocyberMKIIEpic',
	'AdvancedRavenMicrocyberMKIIEpicPlus', 'AdvancedRavenMicrocyberMKIIILegendary',
	'AdvancedRavenMicrocyberMKIIILegendaryPlus', 'AdvancedRavenMicrocyberMKIIILegendaryPlusPlus',
	'AdvancedRavenMicrocyberMKIRare', 'AdvancedRavenMicrocyberMKIRarePlus',
	'AdvancedReflexRecorderCommon', 'AdvancedReflexRecorderCommonPlus', 'AdvancedReflexRecorderEpic',
	'AdvancedReflexRecorderEpicPlus', 'AdvancedReflexRecorderLegendary',
	'AdvancedReflexRecorderLegendaryPlus', 'AdvancedReflexRecorderLegendaryPlusPlus',
	'AdvancedReflexRecorderRare', 'AdvancedReflexRecorderRarePlus', 'AdvancedReflexRecorderStatsShard',
	'AdvancedReflexRecorderUncommon', 'AdvancedReflexRecorderUncommonPlus',
	'AdvancedReinforcedMusclesEpic', 'AdvancedReinforcedMusclesEpicPlus',
	'AdvancedReinforcedMusclesLegendary', 'AdvancedReinforcedMusclesLegendaryPlus',
	'AdvancedReinforcedMusclesLegendaryPlusPlus', 'AdvancedReinforcedMusclesRare',
	'AdvancedReinforcedMusclesRarePlus', 'AdvancedReinforcedMusclesStatsShard',
	'AdvancedReinforcedMusclesUncommon', 'AdvancedReinforcedMusclesUncommonPlus',
	'AdvancedReversePowerInductor', 'AdvancedSandevistanApogee', 'AdvancedSandevistanApogeePlus',
	'AdvancedSandevistanApogeePlusPlus', 'AdvancedSandevistanC1MK1', 'AdvancedSandevistanC1MK1Plus',
	'AdvancedSandevistanC1MK2', 'AdvancedSandevistanC1MK2Plus', 'AdvancedSandevistanC1MK3',
	'AdvancedSandevistanC1MK3Plus', 'AdvancedSandevistanC1MK4', 'AdvancedSandevistanC1MK4Plus',
	'AdvancedSandevistanC1MK4PlusPlus', 'AdvancedSandevistanC2MK1', 'AdvancedSandevistanC2MK1Plus',
	'AdvancedSandevistanC2MK2', 'AdvancedSandevistanC2MK2Plus', 'AdvancedSandevistanC2MK3',
	'AdvancedSandevistanC2MK3Plus', 'AdvancedSandevistanC2MK4', 'AdvancedSandevistanC2MK4Plus',
	'AdvancedSandevistanC2MK4PlusPlus', 'AdvancedSandevistanC3MK3', 'AdvancedSandevistanC3MK3Plus',
	'AdvancedSandevistanC3MK4', 'AdvancedSandevistanC3MK4Plus', 'AdvancedSandevistanC3MK5',
	'AdvancedSandevistanC3MK5Plus', 'AdvancedSandevistanC3MK5PlusPlus', 'AdvancedSandevistanC4MK4',
	'AdvancedSandevistanC4MK4Plus', 'AdvancedSandevistanC4MK5', 'AdvancedSandevistanC4MK5Plus',
	'AdvancedSandevistanC4MK5PlusPlus', 'AdvancedSecondHeartEpic', 'AdvancedSecondHeartEpicPlus',
	'AdvancedSecondHeartLegendary', 'AdvancedSecondHeartLegendaryPlus',
	'AdvancedSecondHeartLegendaryPlusPlus', 'AdvancedSecondHeartStatsShard', 'AdvancedSelfIceEpic',
	'AdvancedSelfIceEpicPlus', 'AdvancedSelfIceLegendary', 'AdvancedSelfIceLegendaryPlus',
	'AdvancedSelfIceLegendaryPlusPlus', 'AdvancedSelfIceRare', 'AdvancedSelfIceRarePlus',
	'AdvancedSelfIceStatsShard', 'AdvancedShockAbsorberCommon', 'AdvancedShockAbsorberCommonPlus',
	'AdvancedShockAbsorberEpic', 'AdvancedShockAbsorberEpicPlus', 'AdvancedShockAbsorberLegendary',
	'AdvancedShockAbsorberLegendaryPlus', 'AdvancedShockAbsorberLegendaryPlusPlus',
	'AdvancedShockAbsorberRare', 'AdvancedShockAbsorberRarePlus', 'AdvancedShockAbsorberStatsShard',
	'AdvancedShockAbsorberUncommon', 'AdvancedShockAbsorberUncommonPlus', 'AdvancedSilverhandTattoo',
	'AdvancedSmartLinkCommon', 'AdvancedSmartLinkCommonPlus', 'AdvancedSmartLinkEpic',
	'AdvancedSmartLinkEpicPlus', 'AdvancedSmartLinkLegendary', 'AdvancedSmartLinkLegendaryPlus',
	'AdvancedSmartLinkLegendaryPlusPlus', 'AdvancedSmartLinkRare', 'AdvancedSmartLinkRarePlus',
	'AdvancedSmartLinkStatsShard', 'AdvancedSmartLinkUncommon', 'AdvancedSmartLinkUncommonPlus',
	'AdvancedSmartLink_Tutorial_Common', 'AdvancedSmartLink_Tutorial_CommonPlus',
	'AdvancedSmartLink_Tutorial_Epic', 'AdvancedSmartLink_Tutorial_EpicPlus',
	'AdvancedSmartLink_Tutorial_Legendary', 'AdvancedSmartLink_Tutorial_LegendaryPlus',
	'AdvancedSmartLink_Tutorial_LegendaryPlusPlus', 'AdvancedSmartLink_Tutorial_Rare',
	'AdvancedSmartLink_Tutorial_RarePlus', 'AdvancedSmartLink_Tutorial_Uncommon',
	'AdvancedSmartLink_Tutorial_UncommonPlus', 'AdvancedSmartStorageCommon',
	'AdvancedSmartStorageEpic', 'AdvancedSmartStorageLegendary', 'AdvancedSmartStorageRare',
	'AdvancedSmartStorageUncommon', 'AdvancedStaminaRegenBoosterCommon',
	'AdvancedStaminaRegenBoosterCommonPlus', 'AdvancedStaminaRegenBoosterEpic',
	'AdvancedStaminaRegenBoosterEpicPlus', 'AdvancedStaminaRegenBoosterLegendary',
	'AdvancedStaminaRegenBoosterLegendaryPlus', 'AdvancedStaminaRegenBoosterLegendaryPlusPlus',
	'AdvancedStaminaRegenBoosterRare', 'AdvancedStaminaRegenBoosterRarePlus',
	'AdvancedStaminaRegenBoosterStatsShard', 'AdvancedStaminaRegenBoosterUncommon',
	'AdvancedStaminaRegenBoosterUncommonPlus', 'AdvancedStrongArmsBase',
	'AdvancedStrongArmsChemicalEpic', 'AdvancedStrongArmsChemicalEpicPlus',
	'AdvancedStrongArmsChemicalLegendary', 'AdvancedStrongArmsChemicalLegendaryPlus',
	'AdvancedStrongArmsChemicalLegendaryPlusPlus', 'AdvancedStrongArmsChemicalRare',
	'AdvancedStrongArmsChemicalRarePlus', 'AdvancedStrongArmsChemicalStatsShard',
	'AdvancedStrongArmsChemicalUncommon', 'AdvancedStrongArmsChemicalUncommonPlus',
	'AdvancedStrongArmsElectricEpic', 'AdvancedStrongArmsElectricEpicPlus',
	'AdvancedStrongArmsElectricLegendary', 'AdvancedStrongArmsElectricLegendaryPlus',
	'AdvancedStrongArmsElectricLegendaryPlusPlus', 'AdvancedStrongArmsElectricRare',
	'AdvancedStrongArmsElectricStatsShard', 'AdvancedStrongArmsElectricUncommon',
	'AdvancedStrongArmsElectricUncommonPlus', 'AdvancedStrongArmsElectric_RarePlus',
	'AdvancedStrongArmsEpic', 'AdvancedStrongArmsEpicPlus', 'AdvancedStrongArmsLegendary',
	'AdvancedStrongArmsLegendaryPlus', 'AdvancedStrongArmsLegendaryPlusPlus', 'AdvancedStrongArmsRare',
	'AdvancedStrongArmsRarePlus', 'AdvancedStrongArmsStatsShard', 'AdvancedStrongArmsThermalEpic',
	'AdvancedStrongArmsThermalEpicPlus', 'AdvancedStrongArmsThermalLegendary',
	'AdvancedStrongArmsThermalLegendaryPlus', 'AdvancedStrongArmsThermalLegendaryPlusPlus',
	'AdvancedStrongArmsThermalRare', 'AdvancedStrongArmsThermalRarePlus',
	'AdvancedStrongArmsThermalStatsShard', 'AdvancedStrongArmsThermalUncommon',
	'AdvancedStrongArmsThermalUncommonPlus', 'AdvancedStrongArmsUncommon',
	'AdvancedStrongArmsUncommonPlus', 'AdvancedSubdermalCoProcessorCommon',
	'AdvancedSubdermalCoProcessorCommonPlus', 'AdvancedSubdermalCoProcessorEpic',
	'AdvancedSubdermalCoProcessorEpicPlus', 'AdvancedSubdermalCoProcessorLegendary',
	'AdvancedSubdermalCoProcessorLegendaryPlus', 'AdvancedSubdermalCoProcessorLegendaryPlusPlus',
	'AdvancedSubdermalCoProcessorRare', 'AdvancedSubdermalCoProcessorRarePlus',
	'AdvancedSubdermalCoProcessorStatsShard', 'AdvancedSubdermalCoProcessorUncommon',
	'AdvancedSubdermalCoProcessorUncommonPlus', 'AdvancedSuddenAidCommon',
	'AdvancedSuddenAidCommonPlus', 'AdvancedSuddenAidEpic', 'AdvancedSuddenAidEpicPlus',
	'AdvancedSuddenAidLegendary', 'AdvancedSuddenAidLegendaryPlus',
	'AdvancedSuddenAidLegendaryPlusPlus', 'AdvancedSuddenAidRare', 'AdvancedSuddenAidRarePlus',
	'AdvancedSuddenAidStatsShard', 'AdvancedSuddenAidUncommon', 'AdvancedSuddenAidUncommonPlus',
	'AdvancedSynapticAcceleratorCommon', 'AdvancedSynapticAcceleratorCommonPlus',
	'AdvancedSynapticAcceleratorEpic', 'AdvancedSynapticAcceleratorEpicPlus',
	'AdvancedSynapticAcceleratorLegendary', 'AdvancedSynapticAcceleratorLegendaryPlus',
	'AdvancedSynapticAcceleratorLegendaryPlusPlus', 'AdvancedSynapticAcceleratorRare',
	'AdvancedSynapticAcceleratorRarePlus', 'AdvancedSynapticAcceleratorStatsShard',
	'AdvancedSynapticAcceleratorUncommon', 'AdvancedSynapticAcceleratorUncommonPlus',
	'AdvancedT1000Common', 'AdvancedT1000Common2', 'AdvancedT1000Epic', 'AdvancedT1000Epic2',
	'AdvancedT1000Epic2Plus', 'AdvancedT1000EpicPlus', 'AdvancedT1000Legendary',
	'AdvancedT1000Legendary2', 'AdvancedT1000Legendary2Plus', 'AdvancedT1000Legendary2PlusPlus',
	'AdvancedT1000LegendaryPlus', 'AdvancedT1000LegendaryPlusPlus', 'AdvancedT1000Rare',
	'AdvancedT1000Rare2', 'AdvancedT1000Rare2Plus', 'AdvancedT1000RarePlus', 'AdvancedT1000StatsShard',
	'AdvancedT1000Uncommon', 'AdvancedT1000Uncommon2', 'AdvancedTetratronicRipplerMKICommon',
	'AdvancedTetratronicRipplerMKICommonPlus', 'AdvancedTetratronicRipplerMKIIIRare',
	'AdvancedTetratronicRipplerMKIIIRarePlus', 'AdvancedTetratronicRipplerMKIIUncommon',
	'AdvancedTetratronicRipplerMKIIUncommonPlus', 'AdvancedTetratronicRipplerMKIVEpic',
	'AdvancedTetratronicRipplerMKIVEpicPlus', 'AdvancedTetratronicRipplerMKVLegendary',
	'AdvancedTetratronicRipplerMKVLegendaryPlus', 'AdvancedTetratronicRipplerMKVLegendaryPlusPlus',
	'AdvancedTimeBankLegendary', 'AdvancedTimeBankLegendaryPlus', 'AdvancedTimeBankLegendaryPlusPlus',
	'AdvancedTimeBankStatsShard', 'AdvancedTitaniumInfusedBonesCommon',
	'AdvancedTitaniumInfusedBonesCommon2', 'AdvancedTitaniumInfusedBonesCommon2Plus',
	'AdvancedTitaniumInfusedBonesCommonPlus', 'AdvancedTitaniumInfusedBonesEpic',
	'AdvancedTitaniumInfusedBonesEpic2', 'AdvancedTitaniumInfusedBonesEpic2Plus',
	'AdvancedTitaniumInfusedBonesEpicPlus', 'AdvancedTitaniumInfusedBonesLegendary',
	'AdvancedTitaniumInfusedBonesLegendary2', 'AdvancedTitaniumInfusedBonesLegendary2Plus',
	'AdvancedTitaniumInfusedBonesLegendary2PlusPlus', 'AdvancedTitaniumInfusedBonesLegendaryPlus',
	'AdvancedTitaniumInfusedBonesLegendaryPlusPlus', 'AdvancedTitaniumInfusedBonesRare',
	'AdvancedTitaniumInfusedBonesRare2', 'AdvancedTitaniumInfusedBonesRare2Plus',
	'AdvancedTitaniumInfusedBonesRarePlus', 'AdvancedTitaniumInfusedBonesStatsShard',
	'AdvancedTitaniumInfusedBonesUncommon', 'AdvancedTitaniumInfusedBonesUncommon2',
	'AdvancedTitaniumInfusedBonesUncommon2Plus', 'AdvancedTitaniumInfusedBonesUncommonPlus',
	'AdvancedTroubleFinderCommon', 'AdvancedTroubleFinderCommonPlus', 'AdvancedTroubleFinderEpic',
	'AdvancedTroubleFinderEpicPlus', 'AdvancedTroubleFinderLegendary',
	'AdvancedTroubleFinderLegendaryPlus', 'AdvancedTroubleFinderLegendaryPlusPlus',
	'AdvancedTroubleFinderRare', 'AdvancedTroubleFinderRarePlus', 'AdvancedTroubleFinderStatsShard',
	'AdvancedTroubleFinderUncommon', 'AdvancedTroubleFinderUncommonPlus',
	'AdvancedTyrosineInjectorCommon', 'AdvancedTyrosineInjectorCommonPlus',
	'AdvancedTyrosineInjectorEpic', 'AdvancedTyrosineInjectorEpicPlus',
	'AdvancedTyrosineInjectorLegendary', 'AdvancedTyrosineInjectorLegendaryPlus',
	'AdvancedTyrosineInjectorLegendaryPlusPlus', 'AdvancedTyrosineInjectorRare',
	'AdvancedTyrosineInjectorRarePlus', 'AdvancedTyrosineInjectorStatsShard',
	'AdvancedTyrosineInjectorUncommon', 'AdvancedTyrosineInjectorUncommonPlus', 'AdvancedUncommonDeck',
	'AdvancedUncommonHighEnergyDeck', 'AdvancedUncommonLowEnergyDeck', 'AdvancedUncommonMidEnergyDeck',
	'AdvancedViralVenomCommon', 'AdvancedViralVenomEpic', 'AdvancedViralVenomEpicPlus',
	'AdvancedViralVenomLegendary', 'AdvancedViralVenomLegendaryPlus',
	'AdvancedViralVenomLegendaryPlusPlus', 'AdvancedViralVenomRare', 'AdvancedViralVenomRarePlus',
	'AdvancedViralVenomStatsShard', 'AdvancedViralVenomUncommon', 'AdvancedVisualCortexSupportCommon',
	'AdvancedVisualCortexSupportCommonPlus', 'AdvancedVisualCortexSupportEpic',
	'AdvancedVisualCortexSupportEpicPlus', 'AdvancedVisualCortexSupportLegendary',
	'AdvancedVisualCortexSupportLegendaryPlus', 'AdvancedVisualCortexSupportLegendaryPlusPlus',
	'AdvancedVisualCortexSupportRare', 'AdvancedVisualCortexSupportRarePlus',
	'AdvancedVisualCortexSupportStatsShard', 'AdvancedVisualCortexSupportUncommon',
	'AdvancedVisualCortexSupportUncommonPlus', 'AdvancedWeirdTankyPlatingCommon',
	'AdvancedWeirdTankyPlatingEpic', 'AdvancedWeirdTankyPlatingEpicPlus',
	'AdvancedWeirdTankyPlatingLegendary', 'AdvancedWeirdTankyPlatingLegendaryPlus',
	'AdvancedWeirdTankyPlatingLegendaryPlusPlus', 'AdvancedWeirdTankyPlatingRare',
	'AdvancedWeirdTankyPlatingRarePlus', 'AdvancedWeirdTankyPlatingStatsShard',
	'AdvancedWeirdTankyPlatingUncommon', 'AdvancedWeirdTankyPlatingUncommonPlus',
	'AdvancedYakuzaTattoo', 'AdvancedYakuzaTattooEpic', 'AdvancedYakuzaTattooEpicPlus',
	'AdvancedYakuzaTattooLegendary', 'AdvancedYakuzaTattooLegendaryPlus',
	'AdvancedYakuzaTattooLegendaryPlusPlus', 'AdvancedYakuzaTattooPlus', 'AdvancedYakuzaTattooRare',
	'AdvancedYakuzaTattooRarePlus', 'AdvancedYakuzaTattooUncommon', 'AdvancedYakuzaTattooUncommonPlus',
	'AntiVirus', 'ArasakaEpicMKIII', 'ArasakaLegendaryMKIV', 'ArmsModule', 'BaseDeck', 'BaseDeckTier2',
	'BaseDeckTier3', 'BaseDeckTier4', 'BaseDeckTier5', 'BaseOptics', 'BasePowerGrip',
	'BeginnerCyberdeck', 'BerserkBase', 'BerserkC1MK1', 'BerserkC1MK2', 'BerserkC1MK3', 'BerserkC2MK1',
	'BerserkC2MK2', 'BerserkC2MK3', 'BerserkC2MK4', 'BerserkC3MK4', 'BerserkC3MK5', 'BerserkC4MK5',
	'BioDyneRareMKII', 'BioDyneUncommonMKI', 'BiotechEpicMKIII', 'BiotechRareMKII',
	'BiotechUncommonMKI', 'BloodPumpCommon', 'BloodPumpEpic', 'BloodPumpLegendary', 'BloodPumpRare',
	'BloodPumpUncommon', 'BoostedTendonsRare', 'BrainCapacityBoosterEpic',
	'BrainCapacityBoosterLegendary', 'BrainCapacityBoosterRare', 'CapacityBoosterEpic',
	'CapacityBoosterEpicPlus', 'CapacityBoosterLegendary', 'CapacityBoosterLegendaryPlus',
	'CapacityBoosterLegendaryPlusPlus', 'CapacityBoosterRare', 'CapacityBoosterRarePlus',
	'CapacityBoosterUncommon', 'CapacityBoosterUncommonPlus', 'CardiovascularSystemModule',
	'CasiusTattoo', 'CatPaws', 'CyberRotorsCommon', 'CyberRotorsEpic', 'CyberRotorsLegendary',
	'CyberRotorsRare', 'CyberRotorsUncommon', 'Cyberware', 'CyberwareStatsShard',
	'CyberwareStatsShardCommon', 'CyberwareStatsShardEpic', 'CyberwareStatsShardLegendary',
	'CyberwareStatsShardRare', 'CyberwareStatsShardStatic', 'CyberwareStatsShardUncommon',
	'Debug_Ultimate_Cyberdeck_Epic', 'Debug_Ultimate_Cyberdeck_Legendary', 'DenseMarrowEpic',
	'DenseMarrowRare', 'DenseMarrowUncommon', 'DischargeConnectorEpic', 'DischargeConnectorLegendary',
	'DischargeConnectorRare', 'EP1_Stanalone_StartingBuild_Cyberdeck', 'EndoskeletonEpic',
	'EndoskeletonLegendary', 'EyesModule', 'FastAccessMemoryCommon', 'FastAccessMemoryRare',
	'FastAccessMemoryUncommon', 'FrontalCortexModule', 'FuyutsuiCommonMKI',
	'FuyutsuiTinkererLegendaryMKIII', 'HandsModule', 'Hard_20_Intelligence_Cyberdeck',
	'Hard_20_Intelligence_Monowire', 'Hard_30_IntBody_Cyberdeck', 'HauntedCyberdeck',
	'HauntedCyberdeck_Epic', 'HauntedCyberdeck_EpicPlus', 'HauntedCyberdeck_Legendary',
	'HauntedCyberdeck_LegendaryPlus', 'HauntedCyberdeck_LegendaryPlusPlus', 'HauntedCyberdeck_Rare',
	'HauntedCyberdeck_RarePlus', 'HealOnKillCommon', 'HealOnKillEpic', 'HealOnKillLegendary',
	'HealOnKillUncommon', 'HealthMonitorCommon', 'HealthMonitorEpic', 'HealthMonitorLegendary',
	'HealthMonitorRare', 'HealthMonitorUncommon', 'IconicAdvancedChitonCommon',
	'IconicAdvancedChitonCommonPlus', 'IconicAdvancedChitonEpic', 'IconicAdvancedChitonEpicPlus',
	'IconicAdvancedChitonLegendary', 'IconicAdvancedChitonLegendaryPlus',
	'IconicAdvancedChitonLegendaryPlusPlus', 'IconicAdvancedChitonRare',
	'IconicAdvancedChitonRarePlus', 'IconicAdvancedChitonUncommon', 'IconicAdvancedChitonUncommonPlus',
	'IconicAdvancedDetectorRushEpic', 'IconicAdvancedDetectorRushEpicPlus',
	'IconicAdvancedDetectorRushLegendary', 'IconicAdvancedDetectorRushLegendaryPlus',
	'IconicAdvancedDetectorRushLegendaryPlusPlus', 'IconicAdvancedDetectorRushRare',
	'IconicAdvancedDetectorRushRarePlus', 'IconicAdvancedProximityReducerEpic',
	'IconicAdvancedProximityReducerEpicPlus', 'IconicAdvancedProximityReducerLegendary',
	'IconicAdvancedProximityReducerLegendaryPlus', 'IconicAdvancedProximityReducerLegendaryPlusPlus',
	'IconicAdvancedReflexRecorderEpic', 'IconicAdvancedReflexRecorderEpicPlus',
	'IconicAdvancedReflexRecorderLegendary', 'IconicAdvancedReflexRecorderLegendaryPlus',
	'IconicAdvancedReflexRecorderLegendaryPlusPlus', 'IconicAdvancedReflexRecorderRare',
	'IconicAdvancedReflexRecorderRarePlus', 'IconicAdvancedSubdermalCoProcessorEpic',
	'IconicAdvancedSubdermalCoProcessorEpicPlus', 'IconicAdvancedSubdermalCoProcessorEpicPlus_Regina',
	'IconicAdvancedSubdermalCoProcessorEpic_Regina', 'IconicAdvancedSubdermalCoProcessorLegendary',
	'IconicAdvancedSubdermalCoProcessorLegendaryPlus',
	'IconicAdvancedSubdermalCoProcessorLegendaryPlusPlus',
	'IconicAdvancedSubdermalCoProcessorLegendaryPlus_Regina',
	'IconicAdvancedSubdermalCoProcessorLegendary_Regina', 'IconicAdvancedT1000Common',
	'IconicAdvancedT1000Common2', 'IconicAdvancedT1000Epic', 'IconicAdvancedT1000Epic2',
	'IconicAdvancedT1000Epic2Plus', 'IconicAdvancedT1000EpicPlus', 'IconicAdvancedT1000Legendary',
	'IconicAdvancedT1000Legendary2', 'IconicAdvancedT1000Legendary2Plus',
	'IconicAdvancedT1000Legendary2PlusPlus', 'IconicAdvancedT1000LegendaryPlus',
	'IconicAdvancedT1000LegendaryPlusPlus', 'IconicAdvancedT1000Rare', 'IconicAdvancedT1000Rare2',
	'IconicAdvancedT1000Rare2Plus', 'IconicAdvancedT1000RarePlus', 'IconicAdvancedT1000Uncommon',
	'IconicAdvancedT1000Uncommon2', 'IconicAdvancedVisualCortexSupportCommon',
	'IconicAdvancedVisualCortexSupportCommonPlus', 'IconicAdvancedVisualCortexSupportEpic',
	'IconicAdvancedVisualCortexSupportEpicPlus', 'IconicAdvancedVisualCortexSupportLegendary',
	'IconicAdvancedVisualCortexSupportLegendaryPlus',
	'IconicAdvancedVisualCortexSupportLegendaryPlusPlus', 'IconicAdvancedVisualCortexSupportRare',
	'IconicAdvancedVisualCortexSupportRarePlus', 'IconicAdvancedVisualCortexSupportUncommon',
	'IconicAdvancedVisualCortexSupportUncommonPlus', 'IconicBioConductorsEpic',
	'IconicBioConductorsEpicPlus', 'IconicBioConductorsLegendary', 'IconicBioConductorsLegendaryPlus',
	'IconicBioConductorsLegendaryPlusPlus', 'IconicBioConductorsRare', 'IconicBioConductorsRarePlus',
	'IconicCamilloRamManagerEpic', 'IconicCamilloRamManagerEpicPlus',
	'IconicCamilloRamManagerLegendary', 'IconicCamilloRamManagerLegendaryPlusPlus',
	'IconicCamilloRamManagerLegendaryPlus_1', 'IconicDischargeConnectorEpic',
	'IconicDischargeConnectorEpicPlus', 'IconicDischargeConnectorLegendary',
	'IconicDischargeConnectorLegendaryPlus', 'IconicDischargeConnectorLegendaryPlusPlus',
	'IconicDischargeConnectorRare', 'IconicDischargeConnectorRarePlus', 'IconicGunStabilizerCommon',
	'IconicGunStabilizerCommonPlus', 'IconicGunStabilizerEpic', 'IconicGunStabilizerEpicPlus',
	'IconicGunStabilizerLegendary', 'IconicGunStabilizerLegendaryPlus',
	'IconicGunStabilizerLegendaryPlusPlus', 'IconicGunStabilizerRare', 'IconicGunStabilizerRarePlus',
	'IconicGunStabilizerStatsShard', 'IconicGunStabilizerUncommon', 'IconicGunStabilizerUncommonPlus',
	'IconicJenkinsTendonsEpic', 'IconicJenkinsTendonsEpicPlus', 'IconicJenkinsTendonsLegendary',
	'IconicJenkinsTendonsLegendaryPlus', 'IconicJenkinsTendonsLegendaryPlusPlus',
	'IconicJenkinsTendonsRare', 'IconicJenkinsTendonsRarePlus', 'IconicJenkinsTendonsUncommon',
	'IconicJenkinsTendonsUncommonPlus', 'IconicShockAbsorberEpic', 'IconicShockAbsorberEpicPlus',
	'IconicShockAbsorberLegendary', 'IconicShockAbsorberLegendaryPlus',
	'IconicShockAbsorberLegendaryPlusPlus', 'IconicShockAbsorberRare', 'IconicShockAbsorberRarePlus',
	'Iconic_AdvancedKiroshiOpticsBareBase', 'Iconic_AdvancedKiroshiOpticsBareEpic',
	'Iconic_AdvancedKiroshiOpticsBareEpicPlus', 'Iconic_AdvancedKiroshiOpticsBareLegendary',
	'Iconic_AdvancedKiroshiOpticsBareLegendaryPlus',
	'Iconic_AdvancedKiroshiOpticsBareLegendaryPlusPlus', 'ImmuneSystemModule',
	'IntegumentarySystemModule', 'JointLockEpic', 'JointLockRare', 'KERS', 'KerenzikovCommon',
	'KerenzikovEpic', 'KerenzikovLegendary', 'KerenzikovRare', 'KerenzikovUncommon', 'KiroshiOptics',
	'KiroshiOpticsEpic', 'KiroshiOpticsRare', 'LegsModule', 'MantisBlades', 'MantisBladesEpic',
	'MantisBladesLegendary', 'MaskCW', 'MaskCWPlus', 'MaskCWPlusPlus', 'MaskCW_Base',
	'MaxTac_2nd_wave_Mantis_Blades', 'MemoryBoostCommon', 'MemoryBoostEpic', 'MemoryBoostRare',
	'MemoryBoostUncommon', 'MemoryReplenishmentEpic', 'MemoryReplenishmentLegendary',
	'MilitechParaline', 'MusculoskeletalSystemModule', 'NPC_Mantis_Blades', 'NPC_Strong_Arms',
	'NPC_Strong_Arms_Bennett', 'NanoWires', 'NanoWiresEpic', 'NanoWiresLegendary', 'NanoWiresTest',
	'NeoFiberEpic', 'NeoFiberLegendary', 'NeoFiberRare', 'NeoFiberUncommon', 'NervousSystemModule',
	'NetwatchNetdriverLegendaryMKV', 'Normal_20_Netrunner_Cyberdeck', 'Oda_Mantis_Blades',
	'OpticalCamoEpic', 'OpticalCamoLegendary', 'OpticalCamoRare', 'PainReductor', 'PersonalLink',
	'PlayerTattoo', 'PowerGripEpic', 'PowerGripLegendary', 'PowerGripRare', 'ProjectileLauncher',
	'ProjectileLauncherEpic', 'ProjectileLauncherLegendary', 'Q306_orbital_cyberware',
	'RavenEpicMKIII', 'RavenLegendaryMKIV', 'ReflexRecorderCommon', 'ReflexRecorderLegendary',
	'ReflexRecorderRare', 'ReflexRecorderUncommon', 'ReinforcedMusclesRare', 'RoboticCoreCommon',
	'RoboticCoreEpic', 'RoboticCoreLegendary', 'RoboticCoreRare', 'RoboticCoreUncommon',
	'SandevistanBase', 'SandevistanC1MK1', 'SandevistanC1MK2', 'SandevistanC1MK3', 'SandevistanC2MK1',
	'SandevistanC2MK2', 'SandevistanC2MK3', 'SandevistanC2MK4', 'SandevistanC3MK4', 'SandevistanC3MK5',
	'SandevistanC4MK5', 'SeachoRareMKII', 'SeachoUncommonMKI', 'SecondHeart', 'SilverhandTattoo',
	'SmartLinkEpic', 'SmartLinkLegendary', 'SmartLinkRare', 'StaminaRegenBoosterCommon',
	'StaminaRegenBoosterEpic', 'StaminaRegenBoosterLegendary', 'StaminaRegenBoosterRare',
	'StaminaRegenBoosterUncommon', 'StephensonEpicMKIII', 'StephensonLegendaryMKIV',
	'StephensonRareMKII', 'StrongArms', 'StrongArmsEpic', 'StrongArmsLegendary',
	'SubdermalArmorCommon', 'SubdermalArmorEpic', 'SubdermalArmorLegendary', 'SubdermalArmorRare',
	'SubdermalArmorUncommon', 'SynapticAcceleratorCommon', 'SynapticAcceleratorEpic',
	'SynapticAcceleratorLegendary', 'SynapticAcceleratorRare', 'SynapticAcceleratorUncommon',
	'SystemReplacementModule', 'TetratronicEpicMKIII', 'TetratronicLegendaryTest',
	'TetratronicRareMKII', 'TetratronicRipplerLegendaryMKIV', 'TetratronicUncommonMKI',
	'TitaniumInfusedBonesCommon', 'TitaniumInfusedBonesRare', 'TitaniumInfusedBonesUncommon',
	'Troy_Mantis_Blades', 'TutorialCyberdeck_Course3Stage01', 'TutorialCyberdeck_Course3Stage02',
	'TutorialCyberdeck_Course4Stage04', 'VHard_50_CoolRef_Cyberdeck', 'VHard_50_IntRef_Cyberdeck',
	'VHard_50_IntRef_Monowire', 'VHard_50_IntTech_Cyberdeck', 'VHard_50_IntTech_Monowire',
	'Weak_30_Cyberdeck', 'YakuzaTattoo', 'male_massive_personal_link', 'man_big_personal_link',
	'personal_link', 'scene_personal_link', 'unctionalTestCyberdeck', 'assiveCarryCapacityCyberware',
	'113_smasher_netrunner_cyberdeck',
}
