--- What a garment is called and what it looks like: the fitting room's pictures.
-- @author dop42
--
-- The data is `data/garments-<n>.lua`, GENERATED by `tools/generate-garments.mjs`
-- from the clothing collection the owner staged: record -> the item's own name and
-- the picture of it on each body family, as a file under `web/images/clothing/`.
-- This file is the only thing that reads it, and it is loaded BEFORE the parts so
-- the table they append to exists.
--
-- CHECKED WHEN ASKED, NOT AT LOAD. The parts hold some sixteen hundred rows, and a
-- pass over all of them at load is the same 10,000-instruction ceiling the parts
-- were split to stay under -- spent again for rows the player may never scroll to.
-- A row is checked the first time a box asks for it, and the verdict is kept, so a
-- malformed row costs one journal line and then nothing. The bounds are the ones
-- `modules/inventory/shared/catalog.lua` puts on an item's IMAGE, because both end
-- up in the same `images/` folder through the same `imageFromFile` on the page.
--
-- A RECORD WITH NO ROW IS THE ORDINARY CASE, NOT AN ERROR. The catalogue the room
-- reads is the engine's, and not every record in it has a picture; the box then
-- draws a monogram over a name made from the record, exactly as it did before any
-- picture shipped.

local M = OPX.Modules.Get('appearance')

M.Data = M.Data or {}
-- Filled by the generated parts, one table each. A list of parts rather than one
-- merged table because merging is a loop over every row at load -- see above.
M.Data.GARMENTS = M.Data.GARMENTS or {}

M.Garments = {}
local Garments = M.Garments

--- Pattern and length a picture's file name must have. The same as an item IMAGE.
Garments.FILE = '^[%w_%-%.]+$'
Garments.FILE_MAX = 64

--- Longest name a garment may carry, in bytes. `panel` cuts a tile label to this.
Garments.NAME_MAX = 120

-- record -> the checked row, or false for a record with no usable row.
local checked = {}

-- Records whose row was malformed and has already been reported.
local told = {}

local FILE, FILE_MAX, NAME_MAX = Garments.FILE, Garments.FILE_MAX, Garments.NAME_MAX

--- A usable picture file name, or nil. Absent is not malformed: nil in, nil out.
local function file(value, record)
	if value == nil then return nil end
	if type(value) == 'string' and #value <= FILE_MAX and value:find(FILE) then return value end
	if not told[record] then
		told[record] = true
		-- The module's own journal, which the server keeps: a broken row is a defect
		-- in the generator or a hand edit, and one client's log is not where anybody
		-- would look for it.
		OPX.Note('appearance', ('garment row %s names an unusable picture %q')
			:format(record, tostring(value)))
	end
	return nil
end

--- The checked row for a record, or false.
--
-- THIS IS ON THE SCROLL PATH AND IS COUNTED. A grid window asks it sixty times in
-- one resume, on top of everything `panel` does with the window, and the client
-- kills a resume that overruns its instruction budget without a word. So the row
-- is checked in place rather than copied, the name is taken as the generator
-- wrote it (trimmed there, bounded here), and the parts are walked once. A cold
-- window costs about seventy instructions a box; a warm one, a dozen.
local function row(record)
	local known = checked[record]
	if known ~= nil then return known end
	local raw = nil
	if type(record) == 'string' then
		local parts = M.Data.GARMENTS
		for index = 1, #parts do
			raw = parts[index][record]
			if raw ~= nil then break end
		end
	end
	if type(raw) ~= 'table' then
		checked[record] = false
		return false
	end
	local name = raw.NAME
	if type(name) ~= 'string' or name == '' or #name > NAME_MAX then name = nil end
	local out = { name = name, female = file(raw.FEMALE, record), male = file(raw.MALE, record) }
	if out.name == nil and out.female == nil and out.male == nil then out = false end
	checked[record] = out
	return out
end

--- The item's own name and its picture on a body family, either of them nil.
--
-- The picture is a file name under `images/clothing/`: the family's own first,
-- then the other body's -- a jacket drawn on the wrong body still says which
-- jacket it is -- then nil, which the page draws as a monogram without asking
-- for a file.
-- @param record string an `Items.*` record name
-- @param family string|nil 'female' or 'male'
-- @return string|nil name
-- @return string|nil picture
function Garments.Describe(record, family)
	local found = row(record)
	if not found then return nil, nil end
	if family == 'male' then return found.name, found.male or found.female end
	return found.name, found.female or found.male
end
